### ISSUE TITLE
Error on first and last element of array

### ISSUE THREAD

**Issue by orchidGem** [pinceladasdaweb/CSS3-Perspective-Carousel#4]
There's an error when the slideshow reaches the last array if you're going right and the first array if you're going left. The right and left classes do not get added to the correct elements. I've reworked the code, see screenshot attached for a fix. 

In the move carousel function, remove the reverse calculation of plus one or minus on line 72. Then on the click handler when you use the callback function, redo the calculations. 

![screen shot 2014-12-31 at 12 12 15 pm](https://cloud.githubusercontent.com/assets/9039342/5589522/519caeec-90e6-11e4-9196-f4a558ae12d7.png)

**Comment by pinceladasdaweb** [comment]
@orchidGem 

Submit a pull request, please.

**Comment by pinceladasdaweb** [comment]
Fixed.
