### ISSUE TITLE
AMD Loader

### ISSUE THREAD

**Issue by rollerdead** [pinceladasdaweb/CSS3-Perspective-Carousel#6]
Hello, 
Where i need to put this code?
AMD Loader? 
I already download AMD Plugin https://www.nuget.org/packages/RequireJS.Text/
I'm using Visual Studio 2013.

Installing 'RequireJS 2.1.6'.
Successfully installed 'RequireJS 2.1.6'.
Installing 'RequireJS.Text 2.0.7'.
Successfully installed 'RequireJS.Text 2.0.7'.
Adding 'RequireJS 2.1.6' to HalalNet.
Successfully added 'RequireJS 2.1.6' to HalalNet.
Adding 'RequireJS.Text 2.0.7' to HalalNet.
Successfully added 'RequireJS.Text 2.0.7' to HalalNet.

Which file do i need to paste this code?
require(['/path/to/carousel.min'], function(Carousel) {
    Carousel.init({
        target: $('.carousel')
    });
});

Thanks and nice Carousel!!

**Comment by pinceladasdaweb** [comment]
A note: Do not use the Require.js is required for the plugin to work, let there use option plugin via AMD. You can simply add the plugin page as described in the README will work ok.

**Comment by rollerdead** [comment]
thanks. now it work. thanks alot :dancer:
