### ISSUE TITLE
Tab navigation ?

### ISSUE THREAD

**Issue by acezard** [pinceladasdaweb/CSS3-Perspective-Carousel#9]
Great plugin, but I have an issue.
My client wants to be able to navigate through the carousel by tabbing. It is actually possible to do so, but the tabbing doesnt actually move the slides. If there are more than 3 slides, the tab focus goes to non visible elements.

To fix that, I think it would be great to give right or left class to a non visible element that receives focus.

best regards

**Comment by pinceladasdaweb** [comment]
Navigation via tab is unusual, it would be very confused. There is a fncionalidade of navigation via arrow keys, maybe she does not meet his client.
